## Finding a Good Location for a Gourmet Pizza Place in Cuyahoga County

### Data Sets

For this project I have located population and median income data for Cuyahoga County, OH. This data will be used to see if the demographics are suitable for a gourmet pizza place. This will be combined with Foursquare data to analyze the venues and see what cities have the least competition along with the right demographics. The data is shown below.

In [2]:
import pandas as pd # library for data analsysis
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

I obtained a download of latitude and longitude for all US cities at the following location:
https://simplemaps.com/data/us-cities. I removed the non-Ohio locations and uploaded the CSV. See header below.

In [4]:
df1 = pd.read_csv('OHcities.csv')
df1.head()

           city county      lat      lng  population
0  Dunkinsville  Adams  38.8559 -83.4713         NaN
1   Cherry Fork  Adams  38.8862 -83.6146       155.0
2       Peebles  Adams  38.9463 -83.4094      1753.0
3    West Union  Adams  38.7917 -83.5441      3074.0
4    Manchester  Adams  38.6902 -83.6053      1978.0

I next obtained Ohio median income data from the following website and converted it to a CSV and uploaded it.  https://www.cleveland.com/datacentral/2016/12/median_family_income_household.html. See header below.

In [6]:
df2 = pd.read_csv('OHcities_Income.csv')
df2.head()

          city median_income
0   New Albany     $214,850
1  Indian Hill     $211,795
2  Pepper Pike     $186,765
3       Powell     $146,442
4       Dublin     $144,005

Next, merge the dataframes and remove any city where the median income is $60,000 or less.

In [10]:
df=df1.merge(df2)
df['median_income'] = df['median_income'].str.replace('$', '')
df['median_income'] = df['median_income'].str.replace(',', '')
df['median_income'] = df['median_income'].astype(float)
df=df.loc[df['median_income'] > 60000]
df

,city,county,lat,lng,population,median_income
5,Geneva,Ashtabula,41.8003,-80.9461,7415.0,60741.0
6,Athens,Athens,39.3269,-82.0988,30077.0,62500.0
8,Wapakoneta,Auglaize,40.5676,-84.1917,10628.0,62188.0
11,Monroe,Butler,39.4461,-84.3666,13473.0,84388.0
12,Trenton,Butler,39.4791,-84.4620,12762.0,71410.0
13,Fairfield,Butler,39.3301,-84.5405,42617.0,70086.0
15,Oxford,Butler,39.5058,-84.7440,22344.0,76170.0
21,Columbiana,Columbiana,40.8871,-80.6750,7940.0,62403.0
27,University Heights,Cuyahoga,41.4948,-81.5348,13126.0,84594.0
28,Lakewood,Cuyahoga,41.4824,-81.8008,50279.0,70448.0
29,Richmond Heights,Cuyahoga,41.5589,-81.5029,10421.0,63029.0
30,Shaker Heights,Cuyahoga,41.4744,-81.5496,27448.0,107938.0
31,Brecksville,Cuyahoga,41.3079,-81.6193,13425.0,121974.0
33,Strongsville,Cuyahoga,41.3128,-81.8313,44631.0,102639.0
35,Lyndhurst,Cuyahoga,41.5172,-81.4922,13605.0,81236.0
36,Cleveland Heights,Cuyahoga,41.5112,-81.5636,44633.0,73716.0
37,Parma,Cuyahoga,41.3842,-81.7286,79425.0,62298.0
38,Seven Hills,Cuyahoga,41.3805,-81.6737,11655.0,92235.0
39,Middleburg Heights,Cuyahoga,41.3695,-81.8150,15608.0,80728.0
40,Mayfield Heights,Cuyahoga,41.5175,-81.4534,18731.0,64206.0
41,South Euclid,Cuyahoga,41.5239,-81.5245,21658.0,71158.0
45,North Olmsted,Cuyahoga,41.4150,-81.9190,31817.0,74159.0
46,Olmsted Falls,Cuyahoga,41.3657,-81.9043,8890.0,79699.0
47,Bay Village,Cuyahoga,41.4851,-81.9315,15328.0,109673.0
49,Berea,Cuyahoga,41.3696,-81.8642,18859.0,79306.0
50,Pepper Pike,Cuyahoga,41.4801,-81.4619,6198.0,186765.0
51,Brook Park,Cuyahoga,41.4036,-81.8219,18691.0,60571.0
52,Broadview Heights,Cuyahoga,41.3195,-81.6782,19197.0,99286.0
54,Westlake,Cuyahoga,41.4524,-81.9295,32293.0,103875.0
55,Beachwood,Cuyahoga,41.4759,-81.5030,11707.0,115536.0
59,North Royalton,Cuyahoga,41.3138,-81.7451,30247.0,90771.0
60,Rocky River,Cuyahoga,41.4703,-81.8526,20264.0,100334.0
61,Highland Heights,Cuyahoga,41.5518,-81.4691,8397.0,114792.0
62,Independence,Cuyahoga,41.3780,-81.6385,7114.0,105600.0
63,Solon,Cuyahoga,41.3864,-81.4401,23003.0,113495.0
64,Fairview Park,Cuyahoga,41.4419,-81.8530,16332.0,73688.0
67,Powell,Delaware,40.1679,-83.0800,12810.0,146442.0
68,Delaware,Delaware,40.2870,-83.0749,38643.0,75310.0
70,Huron,Erie,41.3912,-82.5626,6977.0,62113.0
71,Vermilion,Erie,41.4103,-82.3214,10409.0,65316.0
72,Canal Winchester,Fairfield,39.8432,-82.8121,7905.0,91780.0
73,Pickerington,Fairfield,39.8889,-82.7680,20069.0,91230.0
76,Grove City,Franklin,39.8665,-83.0703,39721.0,79132.0
77,Worthington,Franklin,40.0949,-83.0209,14528.0,120128.0
78,New Albany,Franklin,40.0808,-82.7926,10360.0,214850.0
79,Westerville,Franklin,40.1241,-82.9205,38985.0,105371.0
80,Reynoldsburg,Franklin,39.9588,-82.7943,37449.0,71825.0
81,Gahanna,Franklin,40.0251,-82.8638,34956.0,90217.0
82,Grandview Heights,Franklin,39.9793,-83.0409,7628.0,123558.0
83,Hilliard,Franklin,40.0348,-83.1547,34905.0,113388.0
85,Dublin,Franklin,40.1112,-83.1451,45568.0,144005.0
86,Upper Arlington,Franklin,40.0271,-83.0703,34997.0,127734.0
87,Bexley,Franklin,39.9650,-82.9342,13669.0,127007.0
88,Groveport,Franklin,39.8587,-82.8976,5552.0,70424.0
91,Chardon,Geauga,41.5803,-81.2081,8096.0,78150.0
93,Beavercreek,Greene,39.7312,-84.0627,46376.0,101340.0
94,Bellbrook,Greene,39.6384,-84.0865,7128.0,89175.0
97,Blue Ash,Hamilton,39.2478,-84.3824,12228.0,91463.0
98,Montgomery,Hamilton,39.2494,-84.3457,10582.0,130714.0
99,Harrison,Hamilton,39.2570,-84.7883,14411.0,72308.0
101,Madeira,Hamilton,39.1854,-84.3734,9049.0,101794.0
102,Wyoming,Hamilton,39.2295,-84.4814,8517.0,136250.0
103,Deer Park,Hamilton,39.2037,-84.3975,5674.0,69900.0
105,Sharonville,Hamilton,39.2824,-84.4069,13761.0,71373.0
107,Loveland,Hamilton,39.2679,-84.2731,12732.0,88594.0
113,Findlay,Hancock,41.0460,-83.6380,48701.0,61197.0
120,Bellevue,Huron,41.2744,-82.8396,8178.0,65895.0
126,Wickliffe,Lake,41.6072,-81.4690,12689.0,68690.0
127,Kirtland,Lake,41.5969,-81.3406,6773.0,107821.0
128,Eastlake,Lake,41.6581,-81.4323,18134.0,62877.0
130,Mentor,Lake,41.6895,-81.3361,46732.0,86778.0
131,Willowick,Lake,41.6343,-81.4680,14087.0,68938.0
132,Willoughby,Lake,41.6460,-81.4084,22769.0,72160.0
133,Mentor-on-the-Lake,Lake,41.7135,-81.3650,7371.0,60417.0
134,Willoughby Hills,Lake,41.5873,-81.4332,9482.0,74167.0
138,Pataskala,Licking,40.0109,-82.7159,15458.0,78378.0
140,Sheffield Lake,Lorain,41.4884,-82.0978,9004.0,63081.0
141,Oberlin,Lorain,41.2857,-82.2197,8009.0,65819.0
142,Avon,Lorain,41.4485,-82.0187,22805.0,110191.0
143,Amherst,Lorain,41.4022,-82.2303,12078.0,76463.0
144,North Ridgeville,Lorain,41.3851,-82.0194,32983.0,80348.0
147,Avon Lake,Lorain,41.4945,-82.0160,23659.0,102456.0
149,Waterville,Lucas,41.5017,-83.7365,5519.0,89526.0
150,Oregon,Lucas,41.6556,-83.4326,20040.0,72188.0
151,Sylvania,Lucas,41.7100,-83.7082,18909.0,94526.0
152,Maumee,Lucas,41.5695,-83.6635,13874.0,77867.0
157,Canfield,Mahoning,41.0315,-80.7672,7284.0,88916.0
159,Medina,Medina,41.1358,-81.8694,26261.0,79604.0
160,Brunswick,Medina,41.2464,-81.8198,34756.0,74672.0
161,Wadsworth,Medina,41.0287,-81.7324,23136.0,80057.0
163,Troy,Miami,40.0431,-84.2193,25770.0,63082.0
164,Tipp City,Miami,39.9642,-84.1861,9918.0,86132.0
167,Centerville,Montgomery,39.6339,-84.1448,23817.0,89355.0
168,Vandalia,Montgomery,39.8790,-84.1930,15058.0,73172.0
169,Union,Montgomery,39.9102,-84.2962,6606.0,73059.0
170,Miamisburg,Montgomery,39.6323,-84.2725,19968.0,62962.0
171,Oakwood,Montgomery,39.7202,-84.1734,8999.0,121318.0
174,Englewood,Montgomery,39.8643,-84.3071,13502.0,69543.0
175,Kettering,Montgomery,39.6956,-84.1495,55306.0,64776.0
177,Clayton,Montgomery,39.8689,-84.3292,13160.0,80620.0
179,Huber Heights,Montgomery,39.8595,-84.1130,38019.0,62788.0
187,Streetsboro,Portage,41.2396,-81.3456,16272.0,69524.0
188,Aurora,Portage,41.3118,-81.3450,15876.0,98253.0
191,Ontario,Richland,40.7709,-82.6107,6079.0,63354.0
200,North Canton,Stark,40.8742,-81.3971,17365.0,70798.0
205,Louisville,Stark,40.8366,-81.2646,9356.0,64125.0
207,Stow,Summit,41.1765,-81.4344,34711.0,84948.0
208,Norton,Summit,41.0294,-81.6461,12011.0,75740.0
209,Hudson,Summit,41.2399,-81.4408,22251.0,140575.0
210,Cuyahoga Falls,Summit,41.1641,-81.5206,49206.0,65902.0
211,Twinsburg,Summit,41.3221,-81.4451,18877.0,95574.0
212,Fairlawn,Summit,41.1270,-81.6212,7466.0,80104.0
214,Macedonia,Summit,41.3147,-81.4990,11899.0,101313.0
215,New Franklin,Summit,40.9525,-81.5839,14149.0,80476.0
216,Munroe Falls,Summit,41.1385,-81.4344,5052.0,78990.0
217,Green,Summit,40.9483,-81.4757,25673.0,82248.0
218,Tallmadge,Summit,41.1023,-81.4216,17534.0,71172.0
221,Hubbard,Trumbull,41.1593,-80.5682,7579.0,61491.0
222,Cortland,Trumbull,41.3318,-80.7192,6880.0,75602.0
227,Marysville,Union,40.2276,-83.3594,23674.0,79907.0
229,Lebanon,Warren,39.4248,-84.2139,20651.0,68921.0
230,Springboro,Warren,39.5612,-84.2348,18452.0,116573.0
232,Mason,Warren,39.3563,-84.3034,33037.0,118780.0
239,Northwood,Wood,41.6089,-83.4837,5394.0,73531.0
240,Rossford,Wood,41.5831,-83.5692,6570.0,73071.0
241,Bowling Green,Wood,41.3772,-83.6500,32335.0,63063.0
242,Perrysburg,Wood,41.5376,-83.6412,21592.0,104516.0

Finally, filter dataframe to include only cities in Cuyahoga County.

In [13]:
dfcuyahoga=df[df['county'].str.contains("Cuyahoga")]
dfcuyahoga

                  city    county      lat      lng  population  median_income
27  University Heights  Cuyahoga  41.4948 -81.5348     13126.0        84594.0
28            Lakewood  Cuyahoga  41.4824 -81.8008     50279.0        70448.0
29    Richmond Heights  Cuyahoga  41.5589 -81.5029     10421.0        63029.0
30      Shaker Heights  Cuyahoga  41.4744 -81.5496     27448.0       107938.0
31         Brecksville  Cuyahoga  41.3079 -81.6193     13425.0       121974.0
33        Strongsville  Cuyahoga  41.3128 -81.8313     44631.0       102639.0
35           Lyndhurst  Cuyahoga  41.5172 -81.4922     13605.0        81236.0
36   Cleveland Heights  Cuyahoga  41.5112 -81.5636     44633.0        73716.0
37               Parma  Cuyahoga  41.3842 -81.7286     79425.0        62298.0
38         Seven Hills  Cuyahoga  41.3805 -81.6737     11655.0        92235.0
39  Middleburg Heights  Cuyahoga  41.3695 -81.8150     15608.0        80728.0
40    Mayfield Heights  Cuyahoga  41.5175 -81.4534     18731.0        64206.0
41        South Euclid  Cuyahoga  41.5239 -81.5245     21658.0        71158.0
45       North Olmsted  Cuyahoga  41.4150 -81.9190     31817.0        74159.0
46       Olmsted Falls  Cuyahoga  41.3657 -81.9043      8890.0        79699.0
47         Bay Village  Cuyahoga  41.4851 -81.9315     15328.0       109673.0
49               Berea  Cuyahoga  41.3696 -81.8642     18859.0        79306.0
50         Pepper Pike  Cuyahoga  41.4801 -81.4619      6198.0       186765.0
51          Brook Park  Cuyahoga  41.4036 -81.8219     18691.0        60571.0
52   Broadview Heights  Cuyahoga  41.3195 -81.6782     19197.0        99286.0
54            Westlake  Cuyahoga  41.4524 -81.9295     32293.0       103875.0
55           Beachwood  Cuyahoga  41.4759 -81.5030     11707.0       115536.0
59      North Royalton  Cuyahoga  41.3138 -81.7451     30247.0        90771.0
60         Rocky River  Cuyahoga  41.4703 -81.8526     20264.0       100334.0
61    Highland Heights  Cuyahoga  41.5518 -81.4691      8397.0       114792.0
62        Independence  Cuyahoga  41.3780 -81.6385      7114.0       105600.0
63               Solon  Cuyahoga  41.3864 -81.4401     23003.0       113495.0
64       Fairview Park  Cuyahoga  41.4419 -81.8530     16332.0        73688.0

This is the population we will analyze to find the best 2 cities for our 2 new pizza joints.